apiVersion: v2
name: databasement
description: A Helm chart for Datacask - Database backup management application
type: application
version: 0.0.0-dev
appVersion: "0.0.0-dev"
keywords:
  - database
  - backup
  - mysql
  - postgresql
  - mariadb
home: https://hjdyzy.github.io/datacask/
sources:
  - https://github.com/hjdyzy/datacask
maintainers:
  - name: hjdyzy
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/readme: README.md
